name: Tests

on: [push, pull_request]

jobs:
  # Install dependencies
  install:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.1]

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install dependencies
      #   run: npm ci

      # - name: build tsconfig
      #   run: npx gulp build:tsconfig

  # Run components tests
  components:
    runs-on: windows-latest
    needs: [install]

    strategy:
      matrix:
        node-version: [14.1]

    steps:
      - name: Test components
      - uses: actions/checkout@v2

      - name: ls
        run: ls --all