name: Tests

on: [push, pull_request]

jobs:
  # Install dependencies
  install:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.1]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build tsconfig
        run: npx gulp build:tsconfig

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./

  # Run components tests
  components:
    runs-on: windows-latest
    needs: [install]

    strategy:
      matrix:
        node-version: [14.1]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact

      - name: Run components tests
        run: npx gulp test:components

  # Run typescript check
  typescript:
    runs-on: windows-latest
    needs: [install]

    strategy:
      matrix:
        node-version: [14.1]

    steps:
      - uses: actions/download-artifact@v2
        with:
          build-artifact

      - uses: actions/checkout@v2
      - name: Run typescript check
        run: node ts-check.js
