name: Test runner

on: [push, pull_request]

jobs:
  typescript:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.1]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: build tsconfig
        run: npx gulp build:tsconfig

      - name: Components test
        run: npx gulp test:components